pragma Singleton
import QtQuick

// Colors come from ThemeColors.qml, generated by scripts/theme.py.
QtObject {
    property color colBg:  ThemeColors.colBg
    property color colFg:  ThemeColors.colFg
    property color colHov: ThemeColors.colHov

    property string fontFamily: "JetBrainsMonoNLNerdFontPropo"
    property int fontSize: 16
}
