wallpaper {
    monitor = eDP-1
    path = ~/dotfiles/wallpapers/Minecraft_Fall_Drop_Campaign_Key_Art_DotNet_Downloadable_Wallpaper_2058x1440.png
    fit_mode = cover
}
splash = false
wallpaper {
    monitor = eDP-2
    path = ~/dotfiles/wallpapers/Minecraft_Fall_Drop_Campaign_Key_Art_DotNet_Downloadable_Wallpaper_2058x1440.png
    fit_mode = cover
}
