-- Theme colors, generated by scripts/theme.py from palette/<flavour>.json.
-- DO NOT EDIT BY HAND — run scripts/theme.py to regenerate.
-- require()d from hyprland.lua.

local M = {
    active_border   = "rgba(b4befeee)",
    inactive_border = "rgba(6c7086aa)",
    glass_tint      = 0x1e1e2e67,
}

return M
